language: perl
install:
  - cpanm -n Dist::Zilla Config::AutoConf Math::Int64 Devel::PPPort
  - dzil authordeps --missing | cpanm -n
script: HARNESS_IS_VERBOSE=1 dzil run prove -lvr t xt
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
